# Generated by Django 4.0.6 on 2022-10-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KaggleTestInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaggle_id', models.IntegerField()),
                ('perc_premium_paid_by_cash_credit', models.FloatField()),
                ('age_in_days', models.IntegerField()),
                ('income', models.IntegerField()),
                ('Count_3_to_6_months_late', models.SmallIntegerField()),
                ('Count_6_to_12_months_late', models.SmallIntegerField()),
                ('Count_more_than_12_months_late', models.SmallIntegerField()),
                ('application_underwriting_score', models.FloatField()),
                ('no_of_premiums_paid', models.SmallIntegerField()),
                ('sourcing_channel', models.CharField(max_length=5)),
                ('residence_area_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KaggleTrainInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaggle_id', models.IntegerField()),
                ('perc_premium_paid_by_cash_credit', models.FloatField()),
                ('age_in_days', models.IntegerField()),
                ('income', models.IntegerField()),
                ('Count_3_to_6_months_late', models.SmallIntegerField()),
                ('Count_6_to_12_months_late', models.SmallIntegerField()),
                ('Count_more_than_12_months_late', models.SmallIntegerField()),
                ('application_underwriting_score', models.FloatField()),
                ('no_of_premiums_paid', models.SmallIntegerField()),
                ('sourcing_channel', models.CharField(max_length=5)),
                ('residence_area_type', models.CharField(max_length=50)),
                ('premium', models.FloatField()),
                ('target', models.SmallIntegerField()),
            ],
        ),
    ]
