# Generated by Django 4.0.6 on 2022-10-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kaggletestinsurance',
            options={'verbose_name_plural': 'Test (Insurance) data from Kaggle'},
        ),
        migrations.AlterModelOptions(
            name='kaggletraininsurance',
            options={'verbose_name_plural': 'Train (Insurance) data from Kaggle'},
        ),
    ]
