# Generated by Django 4.0.6 on 2022-10-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceDashboard', '0002_alter_kaggletestinsurance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaggleRegionInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=15)),
                ('bmi', models.FloatField()),
                ('children', models.IntegerField()),
                ('smoker', models.BooleanField()),
                ('region', models.CharField(max_length=50)),
                ('charges', models.FloatField()),
            ],
        ),
    ]
