# Generated by Django 4.0.6 on 2022-11-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceDashboard', '0003_kaggleregioninsurance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kaggleregioninsurance',
            options={'verbose_name_plural': 'Region based (Insurance) data from Kaggle'},
        ),
    ]
